### ISSUE TITLE
Kouign-Amann is missing

### ISSUE THREAD

**Issue by UnixJunkie** [coco33920/ocaml-baguettesharp-interpreter#19]
Ce projet ne peut pas etre serieux.
Un tel oubli est criminel et ne peux pas etre francais.

**Comment by coco33920** [comment]
Sorry, the issue was orthographic. 
A bug fix has been merged :+1: 
Thanks for the report

**Comment by UnixJunkie** [comment]
I am not 100% sure about the correct photograph myself !
But, I see that this very important project is well managed.
